spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(bB5a2Z8aIJBnnF16l7a68rAK9pySKPoH7/vShHm1rb3J4zwbP6eEfN7fy14OoLoeBzvhxgNvEKAFiRShrZ7pRIenADLrHpQNt6egbSDajtY1BcWv2aO4KqGv6p0VJv6AHx8j+xSNL+Qp0c/+8PYNq6ELVAu3Sl7gyrUpc40xc8yebMCINO/Dl0E4IC6xkXxqvIKnZaBcbgh8zNwNlvMIEQ==)
    username: ENC(D7CpnyQGSjlaJ047DdjBrImPcf5LSHtd6PaoXnMY8b5JIjfTWTCvQc/yb9v40Hce)
    password: ENC(nmDgDDUW6EJg/EpVwcqJqvStKFbQLtKpounFiorCAlfKH2yCHQJXJrEpx5H6HWX1)

  redis:
    host: localhost
    port: 6379

  sql:
    init:
      mode: always

url:
  base: http://localhost:8080
